### ISSUE TITLE
Would like to control SPA heater but thermostat only supports 48 F to 90 F.

### ISSUE THREAD

**Issue by ballle98** [openhab/openhab-google-assistant#239]
Spa heater has a range from 36F to 104F with 99F being a typical setting.  The google thermostat widget does not work the min max range is specified this way.  Looks like Temperature Control is more flexible - https://developers.google.com/assistant/smarthome/traits/temperaturecontrol

```
value: Thermostat
config:
  useFahrenheit: true
  modes: off=OFF,heat=ON
  thermostatTemperatureRange: 36,104
```
